name: defifundr_mobile
description: Crowdfunding app for DeFi projects
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  http: ^0.13.4
  curl_logger_dio_interceptor: ^0.0.1

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  #?  flutter_bloc is a Flutter package that helps you to easily implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.1.1
  #?  flutter_screenutil is a Flutter package that provides a set of utilities for implementing responsive UI.
  flutter_screenutil: ^5.9.0
  #?  go_router is a Flutter package that allows you to easily manage your app's navigation.
  go_router: ^8.0.1
  #? flutter_svg is a Flutter package for drawing SVG pictures.
  flutter_svg: ^2.0.6
  #? google_fonts is a Flutter package that provides a set of fonts from Google Fonts.
  google_fonts: ^5.0.0
  #? freezed_annotation is a Dart package that provides a set of utilities for generating code for the freezed package.
  freezed_annotation: ^2.2.0

  flutter_native_splash:
    ^2.2.16
  get_it: ^8.0.3
  

dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1
  #? freezed is a code generation library for Dart that helps you to write immutable models with ease.
  freezed: ^2.3.2
  #? build_runner is a Dart package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  build_runner: ^2.3.3

  



#? For information on the generic Dart part of this file, see the
import_sorter:
  emojis: true

#? The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
flutter_native_splash:
  color: "#000000"
  image: "assets/images/splashLogo.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appLogo.png"
