name: defifundr_mobile
description: Crowdfunding app for DeFi projects
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  http: ^0.13.4
  curl_logger_dio_interceptor: ^0.0.1

dependencies:
  bloc: any
  carousel_slider: ^5.0.0
  country_list_pick: ^1.0.1+6
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.2
  currency_picker: ^2.0.21
  email_validator: ^3.0.0
  equatable: ^2.0.5
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.6
  fluttertoast: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^8.0.3
  go_router: ^8.0.1
  google_fonts: ^5.0.0
  intl: ^0.20.2
  pinput: ^5.0.1
  web3auth_flutter: ^6.1.2
  web3dart: ^2.7.3

dev_dependencies:
  #? build_runner is a Dart package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  #? freezed is a code generation library for Dart that helps you to write immutable models with ease.
  freezed: ^2.3.2
  very_good_analysis: ^4.0.0+1

#? For information on the generic Dart part of this file, see the
import_sorter:
  emojis: true

#? The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splashLogo.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appLogo.png"
