name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Run unit tests
        run: flutter test --coverage
      - name: Upload to code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
